name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0.7'
          - '3.1.2'
          - '3.2.4'
          - '3.3.3'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the tests
      run: bundle exec rake test
    - name: Run rubocop
      run: bundle exec rake rubocop
    - name: Run stree
      run: bundle exec rake stree:check
